config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "categories#index"
  resources :categories, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe_id, uniqueness: {scope: :category_id}
  validates :comment, length: {minimum:6, too_short: "must have at least 6 characters"}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, inclusion: {in: 0..10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category

    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class="form-new mt-4">
  <h3>Add a recipe to <%= @category.name %></h3>
  <%= simple_form_for [@category, @bookmark] do |f|%>
    <%= f.input :comment, label: false, placeholder: 'Your comment here...' %>
    <%= f.association :recipe %>
    <%= f.submit 'Add recipe', class: 'btn btn-warning' %>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="banner" style="background-image: url('<%= image_path "banner.jpg" %>')">
  <div>
    <h1>Cookbook</h1>
    <h3>Save your favourite recipes</h3>
  </div>
</div>

<div class="container">
  <div class="title-top">
    <h1>List of Categories</h1>
    <%= link_to "New Category", new_category_path, class: "btn btn-warning" %>
  </div>

  <div class="cards mt-3">
    <% @categories.each do |category| %>
      <% if category.photo.attached? %>
        <%= link_to category_path(category) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path category.photo.key, crop: :fill %>')">
            <div>
              <h2><%= category.name %></h2>
              <p><%= category.recipes.count %> recipes</p>
              </div>
            </div>
        <% end %>
      <% else %>
        <%= link_to category_path(category) do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "banner.jpg" %>')">
              <div>
                <h2><%= category.name %></h2>
                <p><%= category.recipes.count %> recipes</p>
                </div>
              </div>
          <% end %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="form-new mt-4">
  <h3>Create a new Category</h3>
  <%= simple_form_for @category do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Create category', class: 'btn btn-warning'  %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @category.photo.key, crop: :fill %>')">
  <div>
    <h1><%=@category.name %></h1>
  </div>
</div>

<div class="container">
  <div class="title-top">
  <h1>Recipes</h1>
  <%= link_to "Add a recipe", new_category_bookmark_path(@category), class: "btn btn-warning" %>
  </div>

  <div class="cards">
    <% @category.bookmarks.each do |bookmark| %>

      <div class="card-trip">

        <img src="<%= bookmark.recipe.image_url %>" />

        <%= link_to bookmark_path(bookmark),
        data: { turbo_method: :delete,
        turbo_confirm: "Are you sure you want to remove #{bookmark.recipe.name} from your #{@category.name} list?"},
        class: "btn-delete" do %>

          <i class="fa-solid fa-trash"></i>

        <% end %>

        <div class="card-description">
          <h2><%= bookmark.recipe.name%></h2>
          <p><%= bookmark.recipe.description%></p>
        </div>

       <div class="card-trip-infos">

          <div>
          <i class="fas fa-quote-left me-2"></i><p><%= bookmark.comment %> </p>
          </div>

          <div>
            <%= bookmark.recipe.rating %> <%= '⭐' * bookmark.recipe.rating.to_i %>
          </div>

        </div>

      </div>

    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Cookbook" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= image_tag "logo.png" %>
    <div>
      <%= link_to "Home", root_path %>
      <%= link_to "New Category", new_category_path %>
      </div>
    </div>